apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment-prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
      env: dev
  template:
    metadata:
      labels:
        app: backend
        env: dev
    spec:
      automountServiceAccountToken: false
      containers:
      - name: backend
        image: masungil/env_backend:latest  # You need to build and push this image to a registry
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: dev-config
        volumeMounts:
        - name: db-secrets
          mountPath: /run/secrets
          readOnly: true
      volumes:
      - name: db-secrets
        secret:
          secretName: db-secrets
