apiVersion: v1
kind: Service
metadata:
  name: mariadb-service-hostpath
  labels:
    app: mariadb-hostpath
spec:
  selector:
    app: mariadb-hostpath
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
