apiVersion: v1
kind: Pod
metadata:
  name: my-app-pod
spec:
  containers:
    - name: my-app-container
      image: busybox
      command: 
        - /bin/sh
        - -c
        - |
          env | grep DB_ # 컨테이너의 모든 환경 변수 출력
          echo "--- sleep 1시간 기다림 ---"
          sleep 3600 
      # DB 관련 환경변수만 출력
      env:
        - name: DB_USER     # 파드에서 사용할 환경 변수 이름
          valueFrom:
            secretKeyRef:
              name: my-db-credentials   # 사용할 Secret 이름
              key: DB_USER              # 사용할 Secret의 key
        - name: DB_PASSWORD # 파드에서 사용할 환경 변수 이름
          valueFrom:
            secretKeyRef:
              name: my-db-credentials   # 사용할 Secret 이름
              key: DB_PASSWORD          # 사용할 Secret의 key

# 해당 파드를 실행
#kubectl apply -f pod-with-secret-env.yaml

# 실행 결과 로그를 확인합니다
#kubectl logs my-app-pod

# 파드의 상세 정보를 확인합니다
#kubectl describe pod my-app-pod
#Environment: 환경변수로 전달되는 것을 확인합니다

#파드 내부에 들러가서 환경변수를 직접 확인할 수도 있습니다
#kubectl exec -it my-app-pod -- /bin/sh
#env | grep DB_


#파드를 삭제합니다
#kubectl delete pod my-app-pod
