version: '3.8'

# 로컬 개발 환경을 위한 덮어쓰기 설정
# `docker-compose up` 실행 시 자동으로 docker-compose.yml과 병합됩니다.
services:
  backend:
    # 로컬 머신과 컨테이너의 포트를 연결하여 API에 접근할 수 있도록 합니다.
    ports:
      - "8005:8000"
    # 로컬 소스 코드를 컨테이너 내부의 작업 디렉터리에 마운트합니다.
    # 이를 통해 코드 변경 시 서버가 자동으로 재시작됩니다 (Live Reload).
    volumes:
      - ./backend:/app
    # 개발용 DB 비밀번호는 .env 파일에서 직접 읽어와 환경 변수로 주입합니다.
    environment:
      - DB_PASSWORD=${DB_PASSWORD}

  db:
    # 개발용 데이터베이스를 초기화하기 위한 환경 변수들을 설정합니다.
    environment:
      - MYSQL_ROOT_PASSWORD=1004
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}