version: '3.8'

# 모든 환경에 공통적인 기본 설정
services:
  backend:
    build:
      context: ./backend
    # .env 파일 또는 --env-file 옵션으로 주입될 환경 변수들을 정의합니다.
    environment:
      - APP_MODE=${APP_MODE}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
    depends_on:
      - db

  db:
    image: mariadb:10.5
