version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    # 호스트의 './backend' 디렉토리를 컨테이너의 '/app' 디렉토리와 동기화
    volumes:
      - ./backend:/app

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    # 호스트의 './nginx.conf' 파일을 컨테이너의 '/etc/nginx/nginx.conf' 파일로 덮어쓰기
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # 'ro'는 read-only(읽기 전용) 옵션
