#version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_NAME=kosa_db
      - DB_USER=kosa
      - DB_PASSWORD=1004
    # 호스트의 './backend' 디렉토리를 컨테이너의 '/app' 디렉토리와 동기화
    volumes:
      - ./backend:/app
    depends_on:
      - db

  db:
    image: mariadb:10.5
    restart: always
    # MariaDB 컨테이너를 초기화하기 위한 환경 변수들입니다.
    environment:
      - MYSQL_ROOT_PASSWORD=1004
      - MYSQL_DATABASE=kosa_db
      - MYSQL_USER=kosa
      - MYSQL_PASSWORD=1004
    # 호스트의 './mariadb_data' 디렉토리를 컨테이너의 '/var/lib/mysql' 디렉토리와 동기화
    volumes:
      - ./mariadb_data:/var/lib/mysql

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    # 호스트의 './nginx.conf' 파일을 컨테이너의 '/etc/nginx/nginx.conf' 파일로 덮어쓰기
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro # 'ro'는 read-only(읽기 전용) 옵션
