apiVersion: v1
kind: Pod
metadata:
  name: my-app-pod-volume
spec:
  containers:
    - name: my-app-container
      image: busybox
      command: [ "/bin/sh", "-c", "ls -l /etc/db-credentials && sleep 3600" ]
      volumeMounts:
      - name: db-secret-volume
        mountPath: "/etc/db-credentials" # 이 경로에 Secret 데이터가 파일로 생성됨
        readOnly: true # Secret 볼륨은 읽기 전용으로 마운트하는 것이 보안상 좋음
  volumes:
    - name: db-secret-volume
      secret:
        secretName: my-db-credentials

# 해당 파드를 실행
#kubectl apply -f pod-with-secret-volume.yaml

# 실행 결과 로그를 확인합니다
#kubectl logs my-app-pod-volume

# 파드의 상세 정보를 확인합니다
#kubectl describe pod my-app-pod-volume
# Mounts 속성을 확인 합니다 

#파드 내부에 들러가서 연결된 폴더를  직접 확인할 수도 있습니다
#kubectl exec -it my-app-pod-volume -- /bin/sh
#ls -l /etc/db-credentials


#파드를 삭제합니다
#kubectl delete pod my-app-pod-volume