apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany # 여러 노드에서 읽기/쓰기 가능
  persistentVolumeReclaimPolicy: Retain
  nfs:
    # NFS 서버의 공유 디렉터리 경로
    path: /mnt/nfs/db_data
    # 중요: 이 부분을 실제 Master 노드의 IP 주소로 변경하세요!
    server: 192.168.80.159