apiVersion: v1
kind: Service
metadata:
  name: hostname-svc-nodeport-affinity
spec:
  sessionAffinity: ClientIP
  ports:
    - name: web-port
      port: 80
      targetPort: 80
  selector:
    app: webserver
  type: NodePort

# `sessionAffinity: ClientIP`
# 이 서비스의 가장 핵심적인 설정입니다.
# 세션 어피니티(Session Affinity)는 "세션 고정" 또는 "스티키 세션(Sticky Session)"이라고도 불립니다.
# 기본값(None)은 들어오는 요청을 파드들에게 라운드 로빈(Round-Robin) 방식으로 분산하지만, ClientIP로 설정하면
# 특정 클라이언트 IP에서 오는 모든 요청은 항상 동일한 파드로 전달됩니다.
# 예를 들어, 어떤 사용자가 웹 서비스에 처음 접속했을 때 A 파드로 연결되었다면, 그 사용자가 접속을 끊기 전까지의
# 모든 요청은 계속 A 파드로만 전달됩니다.
# 이는 사용자의 로그인 정보나 장바구니 내용 등을 파드의 메모리에 저장하는 애플리케이션에서 유용합니다. 다른
# 파드로 요청이 분산되면 세션 정보가 유실될 수 있기 때문입니다.

#반드시 사전에 kubectl apply -f deployment-hostname.yaml 명령어으로 디프로이먼트를 실행해야 아래 서비스가 정상적으로 동작합니다.
#kubectl apply -f hostname-svc-nodeport-affinity.yaml 명령어로 적용해야 합니다.
#각 노드에서 curl <NodePort>:8080 을 실행하여 하나의 파드로 요청이 전달되는지 확인할 수 있습니다.

