apiVersion: v1
kind: Service
metadata:
  name: hostname-svc-nodeport
spec:
  ports:
    - name: web-port
      port: 8080
      targetPort: 80
      nodePort: 31000 #외부서 접근 가능한 외부 포트 설정
  selector:
    app: webserver
  type: NodePort


#NodePort에 port을 내가 원하는 포드로 지정할 수 도 있습니다.
#예를 들어, nodePort: 31000 으로 지정하면, 클러스터 외부에서 31000 포트로 접근할 수 있습니다.
