# 사용될 쿠버네티스 API 버전을 지정합니다.
# Pod, Service 등 핵심 오브젝트는 'v1' API 그룹에 속합니다.
apiVersion: v1

# 생성할 리소스의 종류를 지정합니다. 여기서는 'Pod'입니다.
kind: Pod

# 리소스의 부가 정보(이름, 레이블 등)를 정의하는 부분입니다.
metadata:
  # 이 파드에 'run: webserver'라는 키-값 쌍의 레이블을 붙입니다.
  # 레이블은 리소스를 선택하거나 그룹화하는 데 사용됩니다. (예: Service가 이 레이블을 가진 파드들을 찾을 때)
  labels:
    run: webserver

  # 이 파드의 고유한 이름입니다. 네임스페이스 내에서 중복될 수 없습니다.
  name: webserver

# 리소스의 '원하는 상태(Desired State)'를 상세하게 기술하는 부분입니다.
spec:
  # 이 파드에서 실행될 컨테이너들의 목록입니다. 파드는 하나 이상의 컨테이너를 가질 수 있습니다.
  containers:
  # 첫 번째 컨테이너에 대한 정의
  - # 컨테이너를 생성하는 데 사용할 도커 이미지입니다. 'nginx'는 Docker Hub의 공식 이미지를 의미합니다.
    image: nginx

    # 파드 내에서 컨테이너를 식별하기 위한 이름입니다.
    name: webserver

    # 컨테이너가 노출할 포트 목록입니다.
    ports:
    # 컨테이너의 80번 포트를 개방합니다.
    # 주의: 이것은 컨테이너 내부의 포트를 여는 것이며, 파드 외부로 노출하려면 'Service' 오브젝트가 필요합니다.
    - containerPort: 80

    # 컨테이너가 사용할 리소스(CPU, 메모리)를 설정하는 곳입니다.
    # {}로 비어있다는 것은 리소스 요청(requests) 및 제한(limits)을 설정하지 않았음을 의미합니다.
    resources: {}

  # 파드의 DNS 정책을 설정합니다.
  # 'ClusterFirst'는 파드의 DNS 쿼리가 먼저 클러스터 내부의 DNS(예: CoreDNS)로 전달됨을 의미합니다.
  # 클러스터 내부에서 서비스 이름을 찾지 못하면, 노드에 설정된 외부 DNS 서버로 쿼리가 전달됩니다.
  dnsPolicy: ClusterFirst

  # 파드 내의 컨테이너가 종료되었을 때의 재시작 정책입니다.
  # 'Always'는 컨테이너가 어떤 이유로든 종료되면 항상 재시작함을 의미합니다. (기본값)
  # 다른 옵션: 'OnFailure'(오류로 종료될 때만 재시작), 'Never'(재시작 안 함)
  restartPolicy: Always

# 리소스의 '현재 상태(Current State)'를 나타내는 부분입니다.
# 이 필드는 사용자가 설정하는 것이 아니라, 파드가 생성된 후 쿠버네티스에 의해 채워지고 관리됩니다.
# (예: 파드의 IP 주소, 현재 실행 단계(Phase), 컨디션 등)
status: {}