apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      automountServiceAccountToken: false
      containers:
      - name: backend
        image: masungil/env_backend:dev
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: backend-config
        volumeMounts:
        - name: db-secrets
          mountPath: /run/secrets
          readOnly: true
      volumes:
      - name: db-secrets
        secret:
          secretName: db-secrets
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      automountServiceAccountToken: false
      containers:
      - name: backend
        image: masungil/env_backend:prod
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: backend-config
        volumeMounts:
        - name: db-secrets
          mountPath: /run/secrets
          readOnly: true
      volumes:
      - name: db-secrets
        secret:
          secretName: db-secrets