apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: dev
spec:
  ports:
  - port: 3306
  selector:
    app: db
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: prod
spec:
  ports:
  - port: 3306
  selector:
    app: db
  clusterIP: None