apiVersion: v1
kind: Pod
metadata:
  name: hostpath-example
spec:
  # 1. `hostPath` 볼륨을 "host-logs" 라는 이름으로 정의합니다.
  volumes:
  - name: host-logs
    hostPath:
      # 노드의 /var/log 경로를 사용합니다.
      path: /var/log
      # 이 경로의 타입이 디렉터리여야 함을 명시합니다. (권장)
      type: Directory

  containers:
  - name: log-reader-container
    image: busybox
    # 컨테이너가 계속 실행되도록 유지합니다.
    command: ["/bin/sh", "-c"]
    args:
    - |
      while true; do
        ls -la /mnt/host-logs
        sleep 5;
      done
    # 2. 위에서 정의한 "host-logs" 볼륨을 컨테이너의 /mnt/host-logs 경로에 마운트합니다.
    volumeMounts:
    - name: host-logs
      mountPath: /mnt/host-logs
      # 읽기 전용으로 마운트하여 보안을 강화합니다.
      readOnly: true
