apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce # MariaDB는 단일 파드만 쓰기 접근
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/mariadb # 파드가 스케줄링될 노드에 이 경로가 존재해야 합니다.
    type: DirectoryOrCreate # 디렉터리가 없으면 생성합니다.
