apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- backend-deployment.yaml
- backend-service.yaml
- db-deployment.yaml
- db-service.yaml
- nginx-deployment.yaml
- nginx-service.yaml
- nginx-configmap.yaml