apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
bases:
- ../../base
patches:
- path: backend-deployment-patch.yaml
  target:
    kind: Deployment
    name: backend-deployment
- path: nginx-deployment-patch.yaml
  target:
    kind: Deployment
    name: nginx-deployment
images:
- name: masungil/env_backend
  newTag: prod
resources:
- configmap.yaml
- secrets.yaml
- namespace.yaml